### PR TITLE
Networkid fix, Dynamic versioning, Clean up

### PR DESCRIPTION
**Pull request by kyriediculous**
As promised.

Fixed
* --networkid flag 
* Geth & swarm versioning (now latest through PPA repo) 
* Cleaned up docker-compose 
* Removed RPC api from sealers for more "real-world" scenario.
* Exposed 1 Tx node at localhost:8545 instead (locked) so use truffleHDProvider to deploy
* 2 Swarm nodes instead of the 3 I previously ran
* Updated Readme

```
    dev: {
      provider: _ => new HDWalletProvider(<12 word mnemonic>, "http://localhost:8545"),
      network_id: "6660001",
      gasPrice: 0
    },
```

### CODE REVIEW

**Comment by javahippie** [comment]
Thank you for the PR, that's nice. I already created a PR for the Network ID, but I can retract it, that's fine. 

The one thing I am not sure about is hiding the ports to the sealer nodes, I am just not sure what the benefit is. It is a little closer to the real world, but as it is a development chain, I would like to offer as much choice to the developers as possible. Changing the 8545 Port to the (locked) third node and removing the other nodes might possibly break usecases of people relying on this project.

Could you please adress the issue numbers in the text above?

**Comment by kyriediculous** [comment]
I didn't see an added benefit of having three nodes exposed because there is no load balancing between them. 

Afaik other local development environments offer only a single node as well. 

The other benefit is that other developers can easily add light nodes and other nodes to this project and test synchronization in a scenario that resembles real-world configuration. It also makes sure the network propogates raw transactions that are remotely signed. 

Additionally there's not many private network production configs readily available. Resembling this in a test environment would be good for educational purposes as well. 

A last thing is that it prevents the network to be synchronized while it isn't because we mostly only query a single node. Now our node only acts as a relay and the non-exposed sealers need to pick up the gossip and mine the transaction autonomously. 

That was kind of my train of thought, then again re-exposing rpc on the sealers isn't a big change. 

Perhaps a second tx-node that is load balanced would be a nice feature for next upgrade.

**Comment by javahippie** [comment]
That sounds reasonable, I can agree on that. In the future it would be great if we could agree on new features and enhancements in created issues, not in Pull Requests, to give the project a little more structure ;)

**Comment by kyriediculous** [comment]
Yes, you're right. My bad, apologies :).

**Pull request merged**
