### PR TITLE
Explorer, Backend fixes, Geth 1.8.16, Swarm 0.3.4

### PR DESCRIPTION
**Pull request by kyriediculous**

### CODE REVIEW

**Comment by javahippie** [comment]
Checked out the Repo and giving it a continuous test run for some time, looks promising so far! Could you resolve the merge conflict?

**Comment by javahippie** [comment]
After some test runs, this is looking good to me, with two open questions on my side:

1.  When we adapt the eth-explorer as the new monitor, I would throw the two dockerfiles for the old monitor out
2. The number of nodes is growing pretty fast. I know, that creating separate swarm nodes was my idea, too, at first. But I think it would be possible to add swarm to the existing miner and node images, wouldn't it?

Again, thank you very much for your help and effort, it is much appreciated!

**Comment by javahippie** [comment]
Resolved the merge, will accept the PR into develop and incorporate the changes into the next release, thank you very much for your contribution!

**Comment by kyriediculous** [comment]
Sorry , been incredibly busy and we're also putting this in Kubernetes. 

We could indeed throw the monitor out but I did update the repo. In fact after running it a while most of the functionalities work except for hashrate and difficulty. It has some things the monitor doesn't have. 

The way we do it with Kubernetes is running 1 pod for a node that has a geth and swarm container with a shared volume.
I'm not sure if this is doable with docker as we'd need 2 CMD commands in 1 Dockerfile.

**Comment by javahippie** [comment]
No worries, everything fine ;)
Starting two processes in Docker is possible, but not idiomatic to Docker, so I will leave the separate images. I pushed to the develop Branch, addressing issues #12, #28, #34. I also made all the images use the ubuntu ppa repository. It seems to be working for me, though I have no real testcase for Swarm, I am afraid. Could you give it a try?

**Pull request merged**
